//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.685, BuildCommit: 61fde72ba2e055974329fddcad4020b94632d855)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 9126.5.5.2.103
//
#ifndef _UINavigationBarPalette_h
#define _UINavigationBarPalette_h
@import Foundation;
#import <UIKit/UIKit.h>

#include "_UINavigationBarLayoutParticipating-Protocol.h"
#include "_UIPointerInteractionAssistant.h"
#include "_UIScrollPocketInteraction.h"

UIKIT_EXTERN API_AVAILABLE(ios(13.4))
@interface _UINavigationBarPalette : UIView <UIPointerInteractionDelegate, _UINavigationBarLayoutParticipating> {
}

// 注: ipsw が生成したプロパティ宣言には setter= が無いため、Swift から代入すると
// set_contentViewMarginType: のような存在しないセレクタを呼んで実行時に落ちる。
// 実際のセレクタ（下の instance methods を参照）に合わせて setter= を補っている。

@property (copy, nonatomic) NSString *assistantIdentifier;
@property (weak, nonatomic) _UIPointerInteractionAssistant *assistant;
@property (nonatomic) _Bool transitioning;
@property (nonatomic) _Bool pinned;
@property (weak, nonatomic) UINavigationItem *owningNavigationItem;
@property (nonatomic, setter=_setContentViewMarginType:) unsigned long long _contentViewMarginType;
@property (nonatomic, setter=_setDisplaysWhenSearchActive:) _Bool _displaysWhenSearchActive;
@property (nonatomic, setter=_setLayoutPriority:) long long _layoutPriority;
@property (readonly, nonatomic) UIView *contentView;
@property (nonatomic) double preferredHeight;
@property (nonatomic) double minimumHeight;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)pointerInteraction:(id)interaction styleForRegion:(id)region;
- (void)pointerInteraction:(id)interaction willExitRegion:(id)region animator:(id)animator;
- (void)_setAssistants;
- (void)addSubview:(id)subview;
- (void)updateProperties;
- (void)_clearAssistants;
- (void)updateLayoutData:(id)data layoutWidth:(double)width;
- (id)pointerInteraction:(id)interaction regionForRequest:(id)request defaultRegion:(id)region;
- (void)_setLayoutPriority:(long long)priority;
- (id)initWithContentView:(id)view;
- (_Bool)isPinned;
- (void)_setDisplaysWhenSearchActive:(_Bool)active;
- (void)_setContentViewMarginType:(unsigned long long)type;
- (void)pointerInteraction:(id)interaction willEnterRegion:(id)region animator:(id)animator;
- (id)init;
- (void)layoutSubviews;

@end

#endif /* _UINavigationBarPalette_h */
